export enum DBConfigEnum {
	DB_TYPE = 'DB_TYPE',
	DB_HOST = 'DB_HOST',
	DB_PORT = 'DB_PORT',
	DB_USERNAME = 'DB_USERNAME',
	DB_PASSWORD = 'DB_PASSWORD',
	DB_DATABASE = 'DB_DATABASE',
	DB_SYNC = 'DB_SYNC',
}

export enum LogConfigEnum {
	LOG_LEVEL = 'LOG_LEVEL',
	LOG_ON = 'LOG_ON',
}

export enum AppConfigEnum {
	APP_PORT = 'APP_PORT',
	SECRET = 'JWT_SECRET',
	APP_URL_PREFIX = 'APP_URL_PREFIX',
}

export enum UploadConfigEnum {
	QI_NIU_ACCESS_KEY = 'QI_NIU_ACCESS_KEY',
	QI_NIU_SECRET_KEY = 'QI_NIU_SECRET_KEY',
	QI_NIU_BUCKET = 'QI_NIU_BUCKET',
	QI_NIU_DOWNLOAD_URL = 'QI_NIU_DOWNLOAD_URL',
}
